name: DFL-Login1 Deb

on:
  workflow_dispatch:
    inputs:
      dfllogin1Branch:
        description: 'DFL-Login1 Branch'
        required: true
        type: string
      packageCloudRepo:
        description: 'Package Cloud Repo'
        required: true
        default: 'testing'
        type: choice
        options:
        - testing
      packageVersion:
        description: 'Package Version'
        required: true
        type: string

jobs:
  build-deb:
    runs-on: ubuntu-24.04

    container:
      image: debian:testing
      env:
        DEBIAN_FRONTEND: noninteractive
        PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

    steps:
      - name: Install basic packages
        run: apt -q update && apt -yy install build-essential equivs git gnupg ruby-full sudo

      - name: Install package cloud
        run: gem install package_cloud

      - uses: actions/checkout@v4
      - name: Install build dependencies
        run: ./scripts/install-build-deps.sh

      - name: Generate deb
        run: ./scripts/build-deb.sh
        env:
          PACKAGE_VERSION: ${{ inputs.packageVersion }}
          DFL_LOGIN1_BRANCH: ${{ inputs.dfllogin1Branch }}

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: ./build/*.deb
          retention-days: 1
      
      - name: Upload package to Package Cloud
        run: package_cloud push nitrux/${{ inputs.packageCloudRepo }}/debian/duke ./build/*.deb